import { CardProps } from "@/components/card/card";
import { CardType } from "@/components/card/card";
import { IconType } from "@/components/card/dish-card-icons";

export const restaurants: CardProps[] = [
    {
        id: "r1",
        type: CardType.RESTAURANT,
        name: "Claro",
        chef: "Ran Shmueli",
        rating: 4,
        image: "/images/restaurants/claro.jpg",
    },
    {
        id: "r2",
        type: CardType.RESTAURANT,
        name: "Kab Kem",
        chef: "Yariv Malili",
        rating: 1,
        image: "/images/restaurants/kab-kem.jpg",
    },
    {
        id: "r3",
        type: CardType.RESTAURANT,
        name: "Messa",
        chef: "Aviv Moshe",
        rating: 1,
        image: "/images/restaurants/messa-2.jpg",
    },
    {
        id: "r4",
        type: CardType.RESTAURANT,
        name: "Nitan Thai",
        chef: "Shahaf Shabtay",
        rating: 1,
        image: "/images/restaurants/nithan-thai.jpg",
    },
    {
        id: "r5",
        type: CardType.RESTAURANT,
        name: "Tiger Lily",
        chef: "Yanir Green",
        rating: 4,
        image: "/images/restaurants/tiger-lily.jpg",
    },
    {
        id: "r6",
        type: CardType.RESTAURANT,
        name: "Ya pan",
        chef: "Yuval Ben Moshe",
        rating: 3,
        image: "/images/restaurants/yapan.jpg",
    },
    {
        id: "r7",
        type: CardType.RESTAURANT,
        name: "Claro",
        chef: "Ran Shmueli",
        rating: 4,
        image: "/images/restaurants/claro-2.jpg",
    },
    {
        id: "r8",
        type: CardType.RESTAURANT,
        name: "Kitchen Market",
        chef: "Yossi Shitrit",
        rating: 1,
        image: "/images/restaurants/kitchen-market-1.png",
    },
    {
        id: "r9",
        type: CardType.RESTAURANT,
        name: "Onza",
        chef: "Yossi Shitrit",
        rating: 1,
        image: "/images/restaurants/pad-ki-mao.jpg",
    },
];


export const dishes: CardProps[] = [
    {
        id: "d1",
        type: CardType.DISH,
        name: "Pad Ki Mao",
        image: "/images/dishes/pad-ki-mao.jpg",
        description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
        price: 88,
        icons: [IconType.VEGAN, IconType.SPICY],
    },
    {
        id: "d2",
        type: CardType.DISH,
        name: "Ta Ma La Ko",
        image: "/images/dishes/ta-ma-la-ko.jpg",
        description: "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut",
        price: 98,
        icons: [IconType.SPICY],
    },
    {
        id: "d3",
        type: CardType.DISH,
        name: "Red Farm",
        image: "/images/dishes/red-farm-2.png",
        description: "Tofu, Spekkoek Peanuts, Spicy Manis, Pear Yakitori",
        price: 98,
        icons: [IconType.VEGETARIAN, IconType.VEGAN],
    },
    {
        id: "d4",
        type: CardType.DISH,
        name: "Pad Ki Mao",
        image: "/images/dishes/pad-ki-mao-2.png",
        description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
        price: 88,
        icons: [IconType.SPICY],
    },
    {
        id: "d5",
        type: CardType.DISH,
        name: "Red Farm",
        image: "/images/dishes/red-farm-2.png",
        description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
        price: 88,
    },
    {
        id: "d6",
        type: CardType.DISH,
        name: "Pad Ki Mao",
        image: "/images/dishes/pad-ki-mao.png",
        description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
        price: 88,
        icons: [IconType.VEGAN, IconType.SPICY],
    },
    {
        id: "d7",
        type: CardType.DISH,
        name: "Ta Ma La Ko",
        image: "/images/dishes/ta-ma-la-ko.jpg",
        description: "Shrimps, Glass Noodles, Kemiri Nuts, Shallots, Lemon Grass, Magic Chili Brown Coconut",
        price: 98,
        icons: [IconType.SPICY],
    },
    {
        id: "d8",
        type: CardType.DISH,
        name: "Red Farm",
        image: "/images/dishes/red-farm.jpg",
        description: "Tofu, Spekkoek Peanuts, Spicy Manis, Pear Yakitori",
        price: 98,
        icons: [IconType.VEGETARIAN, IconType.VEGAN],
    },
    {
        id: "d9",
        type: CardType.DISH,
        name: "Pad Ki Mao",
        image: "/images/dishes/pad-ki-mao-2.jpg",
        description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
        price: 88,
        icons: [IconType.SPICY],
    },
    {
        id: "d10",
        type: CardType.DISH,
        name: "Red Farm",
        image: "/images/dishes/red-farm-2.jpg",
        description: "Green Papaya, Mango, Chukka Chili, Mint, Kaffir lime, Cashew, Akaya Cham sauce",
        price: 88,
    },
];

export const chefs: CardProps[] = [
    {
        id: "c1",
        type: CardType.CHEF,
        name: "Asaf Granit",
        image: "/images/chefs/asaf-granit.png",
        description: "Mediterranean cuisine pioneer",
    },
    {
        id: "c2",
        type: CardType.CHEF,
        name: "Aviv Moshe",
        image: "/images/chefs/aviv-moshe.png",
        description: "Chef of OCD, fine dining expert",
    },
    {
        id: "c3",
        type: CardType.CHEF,
        name: "Yuval Ben Neriah",
        image: "/images/chefs/yuval-ben-neriah.png",
        description: "Asian fusion master",
    },
    {
        id: "c4",
        type: CardType.CHEF,
        name: "Yossi Shitrit",
        image: "/images/chefs/yossi-shitrit.png",
        description: "Chef Yossi Shitrit has been living and breathing his culinary dreams for more than two decades, including running the kitchen in his first restaurant, the fondly-remembered Violet, located in Moshav  Udim. Shitrit's creativity and culinary  acumen born of long experience  are expressed in the every detail of each and every dish.",
    },
    {
        id: "c5",
        type: CardType.CHEF,
        name: "Eyal Shani",
        image: "/images/chefs/eyal-shani.jpg",
        description: "Classic techniques, modern flavors",
    },
    {
        id: "c6",
        type: CardType.CHEF,
        name: "Meir Adoni",
        image: "/images/chefs/meir-adoni.png",
        description: "Bold flavors and creative plates",
    },
    {
        id: "c7",
        type: CardType.CHEF,
        name: "Omer Miller",
        image: "/images/chefs/omer-miller.png",
        description: "Seafood specialist",
    },
    {
        id: "c8",
        type: CardType.CHEF,
        name: "Shahaf Shabtay",
        image: "/images/chefs/shahaf-shabtay.png",
        description: "French & Middle Eastern fusion",
    },
    {
        id: "c9",
        type: CardType.CHEF,
        name: "Nitzan Raz",
        image: "/images/chefs/nitzan-raz.jpg",
        description: "Live-fire cooking expert",
    },
];
